version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: development
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - DEBUG=true
      - RELOAD=true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - FAST_REFRESH=true
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fleet_management_dev

  redis:
    ports:
      - "6379:6379"

